### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by Radeon4650** [Radeon4650/abz.agency.test_task#1]
- [x] 1.1 Tree view
- [x] 2.1 Flask migrations
- [x] 2.2 DB random filling
- [x] 2.3 Twitter Bootstrap
- [x] 2.4 Overall information table
- [x] 2.5 Search implementation
- [x] 2.6 Sort and search with ajax
- [x] 2.7 Flask authentication
- [x] 2.8 Overall information table transfer to restricted area
- [x] 2.9 CRUD operations
- [ ] 2.10 Photo upload
- [x] 2.11 Chief change
- [x] 2.12 Lazy tree loading
- [ ] 2.13 Drag-n-drop chief change
